import json
import os
import numpy as np
import openai

openai.api_key = os.environ.get('OPENAI_API_KEY')
roles_file_path = 'roles.json'
candidates_file_path = 'candidates.json'
with open(roles_file_path, 'r') as file:
    roles_json = json.load(file)

with open(candidates_file_path, 'r') as file:
    candidates_json = json.load(file)

candidates_dict = {entry['id']: {k: v for k,  v in entry.items() if k != 'ID'} for entry in candidates_json}
roles_dict = {entry['id']: {k: v for k, v in entry.items() if k != 'ID'} for entry in roles_json}

# categories = [
#     "Software Engineering", 
#     "Product & Project Management", 
#     "Data Science & Machine Learning", 
#     "Business Operations & Strategy", 
#     "Marketing & Growth", 
#     "Design & User Experience (UX/UI)", 
#     "Customer Success & Sales", 
#     "Operations & Support", 
#     "Engineering Management & Leadership", 
#     "Specialized Engineering"
# ]

# role_category = {}

# role_names = [roles_dict[role_id]['name'] for role_id in roles_dict.keys()]
# roles_text = "\n".join([f"{i+1}. {role}" for i, role in enumerate(role_names)])
# prompt = f"""Categorize the following job titles into one of these categories: {', '.join(categories)}.

# Job Titles:
# {roles_text}

# For each job title, respond in this format: "<Job Title Number>: <Category>"
# """

# response = openai.ChatCompletion.create(
#     model="gpt-3.5-turbo",
#     messages=[
#         {"role": "system", "content": "You are an AI assistant that categorizes job roles based on their titles."},
#         {"role": "user", "content": prompt}
#     ],
#     max_tokens=1000,
#     n=1,
#     stop=None,
#     temperature=0
# )

# response_text = response['choices'][0]['message']['content'].strip()
# for line in response_text.split("\n"):
#     if line and ":" in line:
#         role_number, category = line.split(":", 1)
#         role_number = role_number.strip()
#         category = category.strip()
#         role_id = str(int(role_number) - 1)  # Adjust index to match role_id
#         role_category[role_id] = category

# for role_id, category in role_category.items():
#     print(f"Role '{roles_dict[role_id]['name']}' categorized as '{category}'")










job_categories = {
    'AI Engineer': 'Data Science & Machine Learning',
    'AI Engineer (CV)': 'Data Science & Machine Learning',
    'Account Executive': 'Customer Success & Sales',
    'Actuarial Product Lead': 'Product & Project Management',
    'Application Software Engineer ': 'Software Engineering',
    'Application Software Engineer (please submit to other role)': 'Software Engineering',
    'Applied AI Researcher': 'Data Science & Machine Learning',
    'Art Director, Branding': 'Design & User Experience (UX/UI)',
    'Artist': 'Design & User Experience (UX/UI)',
    'Assistant Controller': 'Operations & Support',
    'Associate': 'Business Operations & Strategy',
    'BDR/SDR': 'Customer Success & Sales',
    'Backend Engineer': 'Software Engineering',
    'Backend Engineer (Go)': 'Software Engineering',
    'Backend Engineer — Data': 'Software Engineering',
    'Backend Platform Engineer (old)': 'Software Engineering',
    'Battery Software Engineer': 'Specialized Engineering',
    'Biogeochemical Modeler': 'Specialized Engineering',
    'BizOps (Sharp)': 'Business Operations & Strategy',
    'Blockchain Architect': 'Specialized Engineering',
    'Brand Designer': 'Design & User Experience (UX/UI)',
    'Brand Graphic Designer': 'Design & User Experience (UX/UI)',
    'Business Development / Partnership Manager': 'Business Operations & Strategy',
    'Business Development Executive': 'Business Operations & Strategy',
    'Business Development Manager': 'Business Operations & Strategy',
    'Business Intelligence Analyst': 'Data Science & Machine Learning',
    'Business Operations (early hire/generalist)': 'Business Operations & Strategy',
    'Business Operations Analyst / Associate': 'Business Operations & Strategy',
    'CNC Programmer': 'Specialized Engineering',
    'CTO': 'Engineering Management & Leadership',
    'Capacitor Mobile App Developer': 'Software Engineering',
    'Careteam Lead': 'Operations & Support',
    'Chief Crafting Officer': 'Engineering Management & Leadership',
    'Chief of Staff': 'Business Operations & Strategy',
    'Community Lead': 'Marketing & Growth',
    'Content Lead': 'Marketing & Growth',
    'Customer Engineer': 'Customer Success & Sales',
    'Customer Success & Operations': 'Customer Success & Sales',
    'Customer Success Manager': 'Customer Success & Sales',
    'Database Engineer (Rust)': 'Software Engineering',
    'Deep Learning Engineer': 'Data Science & Machine Learning',
    'Demand Generation': 'Marketing & Growth',
    'Design (Frontend) Engineer ': 'Software Engineering',
    'Designer / Hacker': 'Design & User Experience (UX/UI)',
    'DevOps Engineer - Infrastructure': 'Dev-Ops',
    'Developer Advocate': 'Customer Success & Sales',
    'Developer Relations (DevRel)': 'Software Engineering',
    'Director of Engineering': 'Engineering Management & Leadership',
    'Distributed Systems Engineer (Backend)': 'Software Engineering',
    'EV Remanufacturing Technician, ARC': 'Operations & Support',
    'Early Hire: Backend / Fullstack Engineering': 'Software Engineering',
    'Early Hire: Product / Fullstack Engineering': 'Software Engineering',
    'Electrical Engineer': 'Specialized Engineering',
    'Embedded Software Engineer': 'Software Engineering',
    'Engagement Manager': 'Customer Success & Sales',
    'Engineer #1': 'Software Engineering',
    'Engineer (Full Stack / ML)': 'Software Engineering',
    'Engineer [Fullstack Web3]': 'Software Engineering',
    'Engineering Leader, Distributed Systems': 'Engineering Management & Leadership',
    'Engineering Manager': 'Engineering Management & Leadership',
    'Engineering Manager (Hands-on)': 'Engineering Management & Leadership',
    'Enterprise Customer Success Manager': 'Customer Success & Sales',
    'Executive Assistant ': 'Operations & Support',
    'Experience Manager': 'Operations & Support',
    'Experienced Cloud Engineer (Data Platform) (old)': 'Dev-Ops',
    'FP&A Manager': 'Operations & Support',
    'Finance Controller': 'Operations & Support',
    'First Engineer - Core Platform': 'Software Engineering',
    'Forward Deployed Engineer': 'Software Engineering',
    'Forward Deployed Engineer (Forge)': 'Software Engineering',
    'Forward Deployed Engineer, Substrate': 'Software Engineering',
    'Forward Deployed Software Engineer (Seoul)': 'Software Engineering',
    'Founding (Staff/Principal) Infrastructure Engineer': 'Software Engineering',
    'Founding AI Engineer': 'Data Science & Machine Learning',
    'Founding Account Executive': 'Engineering Management & Leadership',
    'Founding Backend + API Engineer': 'Software Engineering',
    'Founding Backend Engineer': 'Software Engineering',
    'Founding Backend Engineer ': 'Software Engineering',
    'Founding Backend/Data Engineer': 'Software Engineering',
    'Founding Blockchain + Smart Contract Engineer (EVM/Solidity)': 'Specialized Engineering',
    'Founding Customer Success': 'Customer Success & Sales',
    'Founding Customer Success Manager': 'Customer Success & Sales',
    'Founding Designer': 'Design & User Experience (UX/UI)',
    'Founding Developer Relations Engineer': 'Customer Success & Sales',
    'Founding Director of Client Success': 'Customer Success & Sales',
    'Founding Engineer': 'Software Engineering',
    'Founding Engineer (Applied AI)': 'Data Science & Machine Learning',
    'Founding Engineer (Frontend or Full Stack)': 'Software Engineering',
    'Founding Engineer (Frontend)': 'Software Engineering',
    'Founding Engineer (Full Stack Software)': 'Software Engineering',
    'Founding Engineer (Full-Stack)': 'Software Engineering',
    'Founding Engineer (Senior) / Head of Engineering': 'Engineering Management & Leadership',
    'Founding Engineer - Computer Vision': 'Data Science & Machine Learning',
    'Founding Engineer - Full Stack ': 'Software Engineering',
    'Founding Engineer, Applied AI': 'Data Science & Machine Learning',
    'Founding Engineer, Full-Stack': 'Software Engineering',
    'Founding Engineer, Geospatial': 'Specialized Engineering',
    'Founding Engineer, Product': 'Product & Project Management',
    'Founding Engineer, Senior': 'Software Engineering',
    'Founding Enterprise Account Executive': 'Customer Success & Sales',
    'Founding Field Marketer': 'Marketing & Growth',
    'Founding Front-end Engineer': 'Software Engineering',
    'Founding Frontend (WebGL/ThreeJS) Engineer': 'Software Engineering',
    'Founding Frontend Engineer': 'Software Engineering',
    'Founding Full Stack Engineer': 'Software Engineering',
    'Founding Full Stack Software Engineer': 'Software Engineering',
    'Founding Full-Stack Engineer': 'Software Engineering',
    'Founding Full-Stack Software Engineer': 'Software Engineering',
    'Founding Fullstack Engineer': 'Software Engineering',
    'Founding Fullstack Engineer (Junior)': 'Software Engineering',
    'Founding Fullstack Engineer (Senior)': 'Software Engineering',
    'Founding GTM': 'Marketing & Growth',
    'Founding Growth Lead': 'Marketing & Growth',
    'Founding ML Engineer': 'Data Science & Machine Learning',
    'Founding Marketer': 'Marketing & Growth',
    'Founding Member of Technical Staff': 'Software Engineering',
    'Founding Mobile Engineer': 'Software Engineering',
    'Founding Mobile Software Engineer': 'Software Engineering',
    'Founding Operator': 'Operations & Support',
    'Founding Optics/Laser Engineer': 'Specialized Engineering',
    'Founding Product Designer': 'Design & User Experience (UX/UI)',
    'Founding Product Engineer': 'Product & Project Management',
    'Founding Product Leader': 'Product & Project Management',
    'Founding Robotics Systems Engineer': 'Specialized Engineering',
    'Founding Sales': 'Customer Success & Sales',
    'Founding Senior Engineer (Backend)': 'Software Engineering',
    'Founding Senior Engineer (Frontend)': 'Software Engineering',
    'Founding Senior Engineer (Infrastructure)': 'Software Engineering',
    'Founding Senior Software Engineer, Fullstack': 'Software Engineering',
    'Founding Senior/Staff Engineer': 'Software Engineering',
    'Founding Smart Contract Engineer': 'Specialized Engineering',
    'Founding Software Engineer': 'Software Engineering',
    'Founding Software Engineer / Head of Engineering': 'Engineering Management & Leadership',
    'Founding Software Engineer Infrastructure': 'Software Engineering',
    'Founding Software Engineer, Fullstack': 'Software Engineering',
    'Founding Tech Lead / Engineering Manager': 'Engineering Management & Leadership',
    'Founding ZK Circuit Engineer': 'Specialized Engineering',
    'Front-End Engineer': 'Software Engineering',
    'Front-end Engineer': 'Software Engineering',
    'Frontend (UI) Engineer': 'Software Engineering',
    'Frontend Design Engineer': 'Software Engineering',
    'Frontend Engineer': 'Software Engineering',
    'Full Stack / Front-end Web Developer': 'Software Engineering',
    'Full Stack Engineer': 'Software Engineering',
    'Full Stack Engineer (Frontend Leaning)': 'Software Engineering',
    'Full Stack Engineer - Backend Focused': 'Software Engineering',
    'Full Stack Product Engineer (Backend Leaning)': 'Software Engineering',
    'Full-Stack Engineer': 'Software Engineering',
    'Full-Stack Engineer (Generalist)': 'Software Engineering',
    'Full-Stack Engineer (Mobile App)': 'Software Engineering',
    'Full-Stack Engineer (Software)': 'Software Engineering',
    'Full-Stack Founding Engineer': 'Software Engineering',
    'Full-Stack Product Engineer': 'Software Engineering',
    'Full-Stack Product Engineer ': 'Software Engineering',
    'Full-Stack Software Engineer': 'Software Engineering',
    'Fullstack AI Engineer': 'Data Science & Machine Learning',
    'Fullstack Engineer': 'Software Engineering',
    'Fullstack Engineer (Senior)': 'Software Engineering',
    'Fullstack Software Engineer': 'Software Engineering',
    'Fullstack Software Engineer - Generalist': 'Software Engineering',
    'Fullstack Software Engineer - ML Focus': 'Data Science & Machine Learning',
    'GPU Kernel Engineer': 'Software Engineering',
    'GTM Lead': 'Marketing & Growth',
    'Game Dev Instructor': 'Specialized Engineering',
    'Game Software Engineer': 'Software Engineering',
    'Gen AI Account Executive': 'Customer Success & Sales',
    'General Counsel': 'Operations & Support',
    'General Manager, ARC': 'Business Operations & Strategy',
    'Generalist Software Engineer': 'Software Engineering',
    'Global Account Manager': 'Customer Success & Sales',
    'Growth': 'Marketing & Growth',
    'Growth & Partnerships Lead': 'Marketing & Growth',
    'Growth Engineer (Acquisition) ': 'Marketing & Growth',
    'Growth Engineer (Business Systems)': 'Marketing & Growth',
    'Growth Manager': 'Marketing & Growth',
    'Growth Marketer': 'Marketing & Growth',
    'Growth Marketing Lead': 'Marketing & Growth',
    'Growth Marketing Manager': 'Marketing & Growth',
    'Growth Marketing Manager - Higher Education': 'Marketing & Growth',
    'Growth/Marketing/Rev Ops ': 'Marketing & Growth',
    'HR Manager': 'Operations & Support',
    'Hacker / Designer': 'Design & User Experience (UX/UI)',
    'Head Bookkeeper': 'Operations & Support',
    'Head of Asia': 'Business Operations & Strategy',
    'Head of BizOps': 'Business Operations & Strategy',
    'Head of Business Development': 'Business Operations & Strategy',
    'Head of Creative': 'Design & User Experience (UX/UI)',
    'Head of Engineering': 'Engineering Management & Leadership',
    'Head of Finance': 'Operations & Support',
    'Head of Government Sales': 'Customer Success & Sales',
    'Head of Growth (AE/SDR)': 'Marketing & Growth',
    'Head of Learning': 'Operations & Support',
    'Head of Manufacturing': 'Operations & Support',
    'Head of Marketing': 'Marketing & Growth',
    'Head of Operations': 'Operations & Support',
    'Head of Operations - Montreal (Fuse)': 'Operations & Support',
    'Head of Recruiting': 'Operations & Support',
    'Head of Risk and Actuary': 'Operations & Support',
    'Head of Sales': 'Marketing & Growth',
    'Head of Sales / Co-Founder': 'Marketing & Growth',
    'Head of Social Content Strategy': 'Marketing & Growth',
    'Infra Engineer': 'Dev-Ops',
    'Infrastructure and Systems Integration Engineer': 'Dev-Ops',
    'Lead Backend Engineer': 'Software Engineering',
    'Lead Brand Designer': 'Design & User Experience (UX/UI)',
    'Lead Full Stack Developer': 'Software Engineering',
    'Lead Product Designer': 'Design & User Experience (UX/UI)',
    'Lead Product Designer (Singapore / Remote)': 'Design & User Experience (UX/UI)',
    'Lead Product Designer (Toronto / Remote)': 'Design & User Experience (UX/UI)',
    'Lead Product Designer (UI/UX)': 'Design & User Experience (UX/UI)',
    'Lead Product Engineer (UI Specialist)': 'Software Engineering',
    'Lead Research Scientist - Enhanced Rock Weathering': 'Specialized Engineering',
    'Lead Software Engineer (AI Agent) ': 'Software Engineering',
    'Lead Technical Account Manager': 'Customer Success & Sales',
    'ML Research Engineer': 'Data Science & Machine Learning',
    'ML Tech Lead (Science and Engineering)': 'Data Science & Machine Learning',
    'ML/AI Instructor': 'Specialized Engineering',
    'MLOps Engineer': 'Dev-Ops',
    'Machine Learning Engineer': 'Data Science & Machine Learning',
    'Machine Learning Infra Engineer': 'Data Science & Machine Learning',
    'Machine Learning Research Engineer': 'Data Science & Machine Learning',
    'Machine Learning Researcher': 'Data Science & Machine Learning',
    'Machine Learning Scientist': 'Data Science & Machine Learning',
    'Marketing Copywriter': 'Marketing & Growth',
    'Marketing Lead': 'Marketing & Growth',
    'Material & Process Engineer': 'Specialized Engineering',
    'Mechanical Design Engineer': 'Specialized Engineering',
    'Mechanical Engineer (Robots, Portals, Autonomous Handoff)': 'Specialized Engineering',
    'Mobile Engineering Lead': 'Software Engineering',
    'Mobile Software Engineer': 'Software Engineering',
    'Mobile Software Engineer - React Native': 'Software Engineering',
    'OSS Engineer - Agent Builder': 'Dev-Ops',
    'Office Manager': 'Operations & Support',
    'Onboarding Manager': 'Customer Success & Sales',
    'Organic Growth Lead': 'Marketing & Growth',
    'PR Manager': 'Marketing & Growth',
    'Partnerships Lead': 'Marketing & Growth',
    'Perception Technical Lead': 'Specialized Engineering',
    'Platform Engineer': 'Dev-Ops',
    'Principal Electrical Engineer': 'Specialized Engineering',
    'Principal Product Designer': 'Design & User Experience (UX/UI)',
    'Principal Software Engineer': 'Software Engineering',
    'Principal Software Engineer - SDE IV': 'Software Engineering',
    'Principal/Staff Front-End Engineer': 'Software Engineering',
    'Process Technician (Thin-film deposition)': 'Specialized Engineering',
    'Product Design Lead': 'Design & User Experience (UX/UI)',
    'Product Designer': 'Design & User Experience (UX/UI)',
    'Product Engineer': 'Product & Project Management',
    'Product Lead': 'Product & Project Management',
    'Product Lead (Full-Stack Engineer)': 'Product & Project Management',
    'Product Manager': 'Product & Project Management',
    'Product Manager (India-based)': 'Product & Project Management',
    'Product Marketing Lead': 'Marketing & Growth',
    'Product Marketing Manager': 'Marketing & Growth',
    'Product Security Engineer': 'Dev-Ops',
    'Product Support Engineer': 'Customer Success & Sales',
    'Python Framework Developer': 'Software Engineering',
    'Quality Manager': 'Operations & Support',
    'React Native / Mobile / Front-End Developer': 'Software Engineering',
    'Remote - Founding Full Stack Engineer (Backend Leaning)': 'Software Engineering',
    'Research Engineer': 'Data Science & Machine Learning',
    'Risk & Underwriting': 'Operations & Support',
    'Robotics Engineer': 'Specialized Engineering',
    'SRE / HPC Engineer': 'Dev-Ops',
    'Sales Consultant': 'Marketing & Growth',
    'Sales Development Representative': 'Marketing & Growth',
    'Sales Development Representative ': 'Marketing & Growth',
    'Sales Engineer': 'Marketing & Growth',
    'Security-Focused Engineer': 'Software Engineering',
    'Senior AI Engineer': 'Data Science & Machine Learning',
    'Senior Analyst': 'Operations & Support',
    'Senior Backend Engineer': 'Software Engineering',
    'Senior Backend Engineer (Go)': 'Software Engineering',
    'Senior Backend Engineer (Rust)': 'Software Engineering',
    'Senior Backend Engineer, Infrastructure': 'Software Engineering',
    'Senior Backend Software Engineer (Marketplace)': 'Software Engineering',
    'Senior Cryptography Engineer': 'Specialized Engineering',
    'Senior Data Engineer (Ads, BizOps & LLMs)': 'Data Science & Machine Learning',
    'Senior Data Scientist - Consumer Products': 'Data Science & Machine Learning',
    'Senior DevOps Engineer': 'Dev-Ops',
    'Senior Engineer, Brazil': 'Software Engineering',
    'Senior Front End Engineer/Tech Lead': 'Software Engineering',
    'Senior Frontend Engineer': 'Software Engineering',
    'Senior Full Stack Engineer': 'Software Engineering',
    'Senior Full Stack Software Engineer': 'Software Engineering',
    'Senior Full-Stack Engineer': 'Software Engineering',
    'Senior Fullstack Engineer': 'Software Engineering',
    'Senior Graphics Engineer': 'Software Engineering',
    'Senior Marketing Manager': 'Marketing & Growth',
    'Senior OS Engineer': 'Software Engineering',
    'Senior Product / LLM Engineer': 'Data Science & Machine Learning',
    'Senior Product Backend Engineer': 'Product & Project Management',
    'Senior Product Designer': 'Design & User Experience (UX/UI)',
    'Senior Product Designer, Growth': 'Design & User Experience (UX/UI)',
    'Senior Product Engineer': 'Product & Project Management',
    'Senior Product Manager': 'Product & Project Management',
    'Senior Product Manager - Payments': 'Product & Project Management',
    'Senior QA Engineer': 'Software Engineering',
    'Senior Software Engineer': 'Software Engineering',
    'Senior Software Engineer ': 'Software Engineering',
    'Senior Software Engineer (Backend)': 'Software Engineering',
    'Senior Software Engineer (Backend, Rust)': 'Software Engineering',
    'Senior Software Engineer (Full Stack)': 'Software Engineering',
    'Senior Software Engineer (Full Stack) - India': 'Software Engineering',
    'Senior Software Engineer (Fullstack)': 'Software Engineering',
    'Senior Software Engineer (Game Server)': 'Software Engineering',
    'Senior Software Engineer (India)': 'Software Engineering',
    'Senior Software Engineer - Backend': 'Software Engineering',
    'Senior Software Engineer, Backend': 'Software Engineering',
    'Senior Software Engineer, Evaluation': 'Software Engineering',
    'Senior Software Engineer, Frontend': 'Software Engineering',
    'Senior Software Engineer, Growth': 'Software Engineering',
    'Senior Software Engineer, Machine Learning Infrastructure': 'Data Science & Machine Learning',
    'Senior Software Engineer, Risk': 'Software Engineering',
    'Senior Solutions Consultant': 'Customer Success & Sales',
    'Senior Unity Engineer': 'Software Engineering',
    'Senior iOS Engineer': 'Software Engineering',
    'Senior/Staff Infrastructure Engineer': 'Dev-Ops',
    'Senior/Staff Software Engineer (C++)': 'Software Engineering',
    'Senior/Staff UX Designer': 'Design & User Experience (UX/UI)',
    'Site Reliability Engineer': 'Dev-Ops',
    'Site Reliability Engineer (Sydney)': 'Dev-Ops',
    'Social Media & Community Lead': 'Marketing & Growth',
    'Social Media Genius': 'Marketing & Growth',
    'Social Media Manager': 'Marketing & Growth',
    'Software Engineer': 'Software Engineering',
    'Software Engineer (AI)': 'Data Science & Machine Learning',
    'Software Engineer (Backend)': 'Software Engineering',
    'Software Engineer (Data/ML Platform)': 'Data Science & Machine Learning',
    'Software Engineer (Developer Experience)': 'Software Engineering',
    'Software Engineer (Frontend)': 'Software Engineering',
    'Software Engineer (Full-Stack / Mobile)': 'Software Engineering',
    'Software Engineer (Full-Stack)': 'Software Engineering',
    'Software Engineer (General)': 'Software Engineering',
    'Software Engineer (Infrastructure/DevOps)': 'Dev-Ops',
    'Software Engineer (Product, Design)': 'Software Engineering',
    'Software Engineer (Recent Grad)': 'Software Engineering',
    'Software Engineer (Typescript)': 'Software Engineering',
    'Software Engineer (iOS)': 'Software Engineering',
    'Software Engineer - Developer Productivity (London)': 'Software Engineering',
    'Software Engineer - Developer Productivity (Palo Alto)': 'Software Engineering',
    'Software Engineer - Frontend': 'Software Engineering',
    'Software Engineer - Frontend / Fullstack': 'Software Engineering',
    'Software Engineer - Frontend Developer Productivity': 'Software Engineering',
    'Software Engineer - Frontend Developer Productivity (London)': 'Software Engineering',
    'Software Engineer - LLM Dataset': 'Data Science & Machine Learning',
    'Software Engineer - Mobile iOS': 'Software Engineering',
    'Software Engineer - Production': 'Software Engineering',
    'Software Engineer - old': 'Software Engineering',
    'Software Engineer, AI R&D': 'Data Science & Machine Learning',
    'Software Engineer, Core Platform': 'Software Engineering',
    'Software Engineer, Distributed Systems (Core)': 'Software Engineering',
    'Software Engineer, Founding Team': 'Software Engineering',
    'Software Engineer, Frontend': 'Software Engineering',
    'Software Engineer, Full Stack': 'Software Engineering',
    'Software Engineer, Infrastructure': 'Software Engineering',
    'Software Engineer, Machine Learning': 'Data Science & Machine Learning',
    'Software Engineer, Platform': 'Dev-Ops',
    'Software Engineer, Product': 'Product & Project Management',
    'Software Engineer, Product Engineering (Full Stack)': 'Software Engineering',
    'Software Engineer, Systems': 'Software Engineering',
    'Software Engineering Manager': 'Engineering Management & Leadership',
    'Solutions Architect': 'Product & Project Management',
    'Solutions Engineer': 'Product & Project Management',
    'Sr. Electrical Engineer - System-wide Embedded Robotics': 'Specialized Engineering',
    'Sr. Full Stack Engineer': 'Software Engineering',
    'Staff AI/ML Engineer': 'Data Science & Machine Learning',
    'Staff Backend/SRE/DevOps Engineer': 'Dev-Ops',
    'Staff Data Engineer': 'Data Science & Machine Learning',
    'Staff Engineer / Tech Lead': 'Engineering Management & Leadership',
    'Staff Frontend Engineer (React, TypeScript)': 'Software Engineering',
    'Staff Full Stack Engineer': 'Software Engineering',
    'Staff Fullstack Engineer': 'Software Engineering',
    'Staff Mechanical Engineer': 'Specialized Engineering',
    'Staff Platform Engineer': 'Dev-Ops',
    'Staff Software Engineer': 'Software Engineering',
    'Staff Software Engineer (Cloud Security)': 'Dev-Ops',
    'Staff Software Engineer (Forward Deployed)': 'Software Engineering',
    'Staff Software Engineer (iOS)': 'Software Engineering',
    'Staff Software Engineer, Backend': 'Software Engineering',
    'Staff Software Engineer, Discovery': 'Software Engineering',
    'Staff Software Engineer, Frontend': 'Software Engineering',
    'Support Engineer': 'Product & Project Management',
    'System Architect': 'Software Engineering',
    'Tech Lead': 'Engineering Management & Leadership',
    'Tech Lead ': 'Engineering Management & Leadership',
    'Tech Lead / Senior Engineer': 'Engineering Management & Leadership',
    'Technical Marketer (First Marketing Hire)': 'Marketing & Growth',
    'Technical Operations Associate': 'Operations & Support',
    'Technical Product Manager': 'Product & Project Management',
    'Technical Support Engineer (Full-stack)': 'Software Engineering',
    'Test Role': 'Specialized Engineering',
    'UAV Controls Engineer': 'Specialized Engineering',
    'UI/UX Designer': 'Design & User Experience (UX/UI)',
    'VP of Engineering': 'Engineering Management & Leadership',
    'VP of Growth ': 'Marketing & Growth',
    'VP of Product': 'Product & Project Management',
    'Visual Designer': 'Design & User Experience (UX/UI)',
    'Web Engineer (Typescript, WASM)': 'Software Engineering',
    'Web3 Marketer': 'Marketing & Growth',
    'testing': 'Specialized Engineering'
}

def job_category_mapping(role_name):
    return job_categories[role_name]




